# CREATING READING AND WRITING WITH PANDAS

In [1]:
#We start by importing pandas
import pandas as pd

## Creating Data
There are two core objects in pandas:
a) Dataframe b)Series

A DataFrame is a table. It contains an array of individual entries, each of which has a certain value. Each entry corresponds to a row (or record) and a column.

For example;

In [3]:
pd.DataFrame({"Yes":[141,151],"No":[132,434]})

Yes   No
0  141  132
1  151  434

In this example, the "0, No" entry has the value of 132. The "0, Yes" entry has a value of 141, and so on.

DataFrame entries are not limited to integers. For instance, here's a DataFrame whose values are strings:

In [4]:
pd.DataFrame({"Bob":["Bob was an accomplished lawyer","He worked in the best legal firms"],"Sue":["He is the smartest kid I know","He was a genius"]})

Bob                            Sue
0     Bob was an accomplished lawyer  He is the smartest kid I know
1  He worked in the best legal firms                He was a genius

We are using the pd.DataFrame() constructor to generate these DataFrame objects. The syntax for declaring a new one is a dictionary whose keys are the column names (Bob and Sue in this example), and whose values are a list of entries. This is the standard way of constructing a new DataFrame, and the one you are most likely to encounter.

The dictionary-list constructor assigns values to the column labels, but just uses an ascending count from 0 (0, 1, 2, 3, ...) for the row labels. Sometimes this is OK, but oftentimes we will want to assign these labels ourselves.

The list of row labels used in a DataFrame is known as an Index. We can assign values to it by using an index parameter in our constructor:

In [5]:
pd.DataFrame({"Bob":["Bob was an accomplished lawyer","He worked in the best legal firms"],"Sue":["He is the smartest kid I know","He was a genius"]},
            index=["Lawyer A","Genius A"])

Bob                            Sue
Lawyer A     Bob was an accomplished lawyer  He is the smartest kid I know
Genius A  He worked in the best legal firms                He was a genius

## Series

A Series, by contrast, is a sequence of data values. If a DataFrame is a table, a Series is a list. And in fact you can create one with nothing more than a list:


In [6]:
pd.Series([1,2,4,5,6,7])

0    1
1    2
2    4
3    5
4    6
5    7
dtype: int64

A Series is, in essence, a single column of a DataFrame. So you can assign row labels to the Series the same way as before, using an index parameter. However, a Series does not have a column name, it only has one overall name:

In [7]:
pd.Series([30,35,45], index=["2015 sales","2016 sales","2017 sales"], name="Product A")

2015 sales    30
2016 sales    35
2017 sales    45
Name: Product A, dtype: int64

The Series and the DataFrame are intimately related. It's helpful to think of a DataFrame as actually being just a bunch of Series "glued together". We'll see more of this in the next section of this tutorial.

The Series and the DataFrame are intimately related. It is helpful to think of a DataFrame as actually being just a bunch of Series "glued together". 
We will see more of this in the next section of this tutorial.

## READING FILES

Being able to create a DataFrame or Series by hand is handy. But, most of the time, 
we wont actually be creating our own data by hand. Instead, we will be working with data that already exists.

Data can be stored in any of a number of different forms and formats. 
By far the most basic of these is the humble CSV

In [ ]:
Product A, Product B, Product C,
30,  25,   56,
56,  65,   76,
45,  67,   65

So a CSV file is a table of values separated by commas. Hence the name: "Comma-Separated Values", or CSV.

Let's now set aside our toy datasets and see what a real dataset looks like when we read it into a DataFrame. We'll use the pd.read_csv() function to read the data into a DataFrame. This goes thusly:

In [11]:
winemag = pd.read_csv("/home/kduah/Desktop/ML/02-Pandas/winemag-data-130k-v2.csv")

In [13]:
#We can use the shape attribute to check how large the resulting DataFrame is:
winemag.shape

(129971, 14)

So our new DataFrame has 130,000 records split across 14 different columns. That's almost 2 million entries!

We can examine the contents of the resultant DataFrame using the head() command, which grabs the first five rows:

In [14]:
winemag.head()

Unnamed: 0   country                                        description  \
0           0     Italy  Aromas include tropical fruit, broom, brimston...   
1           1  Portugal  This is ripe and fruity, a wine that is smooth...   
2           2        US  Tart and snappy, the flavors of lime flesh and...   
3           3        US  Pineapple rind, lemon pith and orange blossom ...   
4           4        US  Much like the regular bottling from 2012, this...   

                          designation  points  price           province  \
0                        Vulkà Bianco      87    NaN  Sicily & Sardinia   
1                            Avidagos      87   15.0              Douro   
2                                 NaN      87   14.0             Oregon   
3                Reserve Late Harvest      87   13.0           Michigan   
4  Vintner's Reserve Wild Child Block      87   65.0             Oregon   

              region_1           region_2         taster_name  \
0                 Etna                NaN       Kerin O’Keefe   
1                  NaN                NaN          Roger Voss   
2    Willamette Valley  Willamette Valley        Paul Gregutt   
3  Lake Michigan Shore                NaN  Alexander Peartree   
4    Willamette Valley  Willamette Valley        Paul Gregutt   

  taster_twitter_handle                                              title  \
0          @kerinokeefe                  Nicosia 2013 Vulkà Bianco  (Etna)   
1            @vossroger      Quinta dos Avidagos 2011 Avidagos Red (Douro)   
2           @paulgwine       Rainstorm 2013 Pinot Gris (Willamette Valley)   
3                   NaN  St. Julian 2013 Reserve Late Harvest Riesling ...   
4           @paulgwine   Sweet Cheeks 2012 Vintner's Reserve Wild Child...   

          variety               winery  
0     White Blend              Nicosia  
1  Portuguese Red  Quinta dos Avidagos  
2      Pinot Gris            Rainstorm  
3        Riesling           St. Julian  
4      Pinot Noir         Sweet Cheeks

The pd.read_csv() function is well-endowed, with over 30 optional parameters you can specify. For example, you can see in this dataset that the CSV file has a built-in index, which pandas did not pick up on automatically. To make pandas use that column for the index (instead of creating a new one from scratch), we can specify an index_col

In [15]:
winemag = pd.read_csv("/home/kduah/Desktop/ML/02-Pandas/winemag-data-130k-v2.csv", index_col=0)
winemag.head()

country                                        description  \
0     Italy  Aromas include tropical fruit, broom, brimston...   
1  Portugal  This is ripe and fruity, a wine that is smooth...   
2        US  Tart and snappy, the flavors of lime flesh and...   
3        US  Pineapple rind, lemon pith and orange blossom ...   
4        US  Much like the regular bottling from 2012, this...   

                          designation  points  price           province  \
0                        Vulkà Bianco      87    NaN  Sicily & Sardinia   
1                            Avidagos      87   15.0              Douro   
2                                 NaN      87   14.0             Oregon   
3                Reserve Late Harvest      87   13.0           Michigan   
4  Vintner's Reserve Wild Child Block      87   65.0             Oregon   

              region_1           region_2         taster_name  \
0                 Etna                NaN       Kerin O’Keefe   
1                  NaN                NaN          Roger Voss   
2    Willamette Valley  Willamette Valley        Paul Gregutt   
3  Lake Michigan Shore                NaN  Alexander Peartree   
4    Willamette Valley  Willamette Valley        Paul Gregutt   

  taster_twitter_handle                                              title  \
0          @kerinokeefe                  Nicosia 2013 Vulkà Bianco  (Etna)   
1            @vossroger      Quinta dos Avidagos 2011 Avidagos Red (Douro)   
2           @paulgwine       Rainstorm 2013 Pinot Gris (Willamette Valley)   
3                   NaN  St. Julian 2013 Reserve Late Harvest Riesling ...   
4           @paulgwine   Sweet Cheeks 2012 Vintner's Reserve Wild Child...   

          variety               winery  
0     White Blend              Nicosia  
1  Portuguese Red  Quinta dos Avidagos  
2      Pinot Gris            Rainstorm  
3        Riesling           St. Julian  
4      Pinot Noir         Sweet Cheeks

## Indexing, Selecting and Assigning

Selecting specific values of a pandas DataFrame or 
Series to work on is an implicit step in almost any data operation you will run, so one of the first things you need to learn in working with data in Python is how to go about selecting the data points relevant to you quickly and effectively.

In [31]:
import pandas as pd
winemag = pd.read_csv('/home/kduah/Desktop/ML/02-Pandas/winemag-data-130k-v2.csv',index_col=0)
pd.set_option('display.max_rows',5)


In Python, we can access the property of an object by accessing it as an attribute. A book object, for example, might have a title property, which we can access by calling book.title. Columns in a pandas DataFrame work in much the same way.

Hence to access the country property of reviews we can use:

In [23]:
winemag.country

0            Italy
1         Portugal
            ...   
129969      France
129970      France
Name: country, Length: 129971, dtype: object

If we have a Python dictionary, we can access its values using the indexing ([]) operator. We can do the same with columns in a DataFrame

In [24]:
winemag['country']

0            Italy
1         Portugal
            ...   
129969      France
129970      France
Name: country, Length: 129971, dtype: object

These are the two ways of selecting a specific Series out of a DataFrame. Neither of them is more or less syntactically valid than the other, but the indexing operator [] does have the advantage that it can handle column names with reserved characters in them (e.g. if we had a country providence column, reviews.country providence wouldn't work).

Doesn't a pandas Series look kind of like a fancy dictionary? It pretty much is, so it's no surprise that, to drill down to a single specific value, we need only use the indexing operator [] once more:

In [25]:
winemag['country'][0]

'Italy'

# Indexing In Pandas

The indexing operator and attribute selection are nice because they work just like they do in the rest of the Python ecosystem. As a novice, this makes them easy to pick up and use. However, pandas has its own accessor operators, [loc and iloc. For more advanced operations, these are the ones you're supposed to be using.]

## Index-based Selection
Pandas indexing works in one of two paradigms. The first is index-based selection: selecting data based on its numerical position in the data. iloc follows this paradigm.

To select the first row of data in a DataFrame, we may use the following

In [26]:
winemag.iloc[0]

country                                                    Italy
description    Aromas include tropical fruit, broom, brimston...
                                     ...                        
variety                                              White Blend
winery                                                   Nicosia
Name: 0, Length: 13, dtype: object

Both loc and iloc are row-first, column-second. This is the opposite of what we do in native Python, which is column-first, row-second.

This means that it's marginally easier to retrieve rows, and marginally harder to get retrieve columns. To get a column with iloc, we can do the following:

In [32]:
winemag.iloc[:,0]

0            Italy
1         Portugal
            ...   
129969      France
129970      France
Name: country, Length: 129971, dtype: object

On its own, the : operator, which also comes from native Python, means "everything". When combined with other selectors, however, it can be used to indicate a range of values. For example, to select the country column from just the first, second, and third row, we would do:

In [33]:
winemag.iloc[:3,0]

0       Italy
1    Portugal
2          US
Name: country, dtype: object

Or, to select just the second and third entries, we would do:

In [34]:
winemag.iloc[1:3,0]

1    Portugal
2          US
Name: country, dtype: object

It's also possible to pass a list:

In [35]:
winemag.iloc[[0,1,2],0]

0       Italy
1    Portugal
2          US
Name: country, dtype: object

Finally, it's worth knowing that negative numbers can be used in selection. This will start counting forwards from the end of the values. So for example here are the last five elements of the dataset.

In [36]:
winemag.iloc[-5:]

country                                        description  \
129966  Germany  Notes of honeysuckle and cantaloupe sweeten th...   
129967       US  Citation is given as much as a decade of bottl...   
129968   France  Well-drained gravel soil gives this wine its c...   
129969   France  A dry style of Pinot Gris, this is crisp with ...   
129970   France  Big, rich and off-dry, this is powered by inte...   

                                   designation  points  price province  \
129966  Brauneberger Juffer-Sonnenuhr Spätlese      90   28.0    Mosel   
129967                                     NaN      90   75.0   Oregon   
129968                                   Kritt      90   30.0   Alsace   
129969                                     NaN      90   32.0   Alsace   
129970           Lieu-dit Harth Cuvée Caroline      90   21.0   Alsace   

       region_1      region_2         taster_name taster_twitter_handle  \
129966      NaN           NaN  Anna Lee C. Iijima                   NaN   
129967   Oregon  Oregon Other        Paul Gregutt           @paulgwine    
129968   Alsace           NaN          Roger Voss            @vossroger   
129969   Alsace           NaN          Roger Voss            @vossroger   
129970   Alsace           NaN          Roger Voss            @vossroger   

                                                    title         variety  \
129966  Dr. H. Thanisch (Erben Müller-Burggraef) 2013 ...        Riesling   
129967                  Citation 2004 Pinot Noir (Oregon)      Pinot Noir   
129968  Domaine Gresser 2013 Kritt Gewurztraminer (Als...  Gewürztraminer   
129969      Domaine Marcel Deiss 2012 Pinot Gris (Alsace)      Pinot Gris   
129970  Domaine Schoffit 2012 Lieu-dit Harth Cuvée Car...  Gewürztraminer   

                                          winery  
129966  Dr. H. Thanisch (Erben Müller-Burggraef)  
129967                                  Citation  
129968                           Domaine Gresser  
129969                      Domaine Marcel Deiss  
129970                          Domaine Schoffit

# Label-based Selection

The second paradigm for attribute selection is the one followed by the loc operator: label-based selection. In this paradigm, it's the data index value, not its position, which matters.

For example, to get the first entry in reviews, we would now do the following:

In [37]:
winemag.loc[0,'country']

'Italy'

iloc is conceptually simpler than loc because it ignores the dataset's indices. When we use iloc we treat the dataset like a big matrix (a list of lists), one that we have to index into by position. loc, by contrast, uses the information in the indices to do its work. Since your dataset usually has meaningful indices, it's usually easier to do things using loc instead. For example, here's one operation that's much easier using loc:

In [38]:
winemag.loc[:,["taster_name","taster_twitter_handle","points"]]

taster_name taster_twitter_handle  points
0       Kerin O’Keefe          @kerinokeefe      87
1          Roger Voss            @vossroger      87
...               ...                   ...     ...
129969     Roger Voss            @vossroger      90
129970     Roger Voss            @vossroger      90

[129971 rows x 3 columns]

## Choosing Between loc and iloc

When choosing or transitioning between loc and iloc, there is one "gotcha" worth keeping in mind, which is that the two methods use slightly different indexing schemes.

iloc uses the Python stdlib indexing scheme, where the first element of the range is included and the last one excluded. So 0:10 will select entries 0,...,9. loc, meanwhile, indexes inclusively. So 0:10 will select entries 0,...,10.

Why the change? Remember that loc can index any stdlib type: strings, for example. If we have a DataFrame with index values Apples, ..., Potatoes, ..., and we want to select "all the alphabetical fruit choices between Apples and Potatoes", then it's a lot more convenient to index df.loc['Apples':'Potatoes'] than it is to index something like df.loc['Apples', 'Potatoet'] (t coming after s in the alphabet).

This is particularly confusing when the DataFrame index is a simple numerical list, e.g. 0,...,1000. In this case df.iloc[0:1000] will return 1000 entries, while df.loc[0:1000] return 1001 of them! To get 1000 elements using loc, you will need to go one lower and ask for df.loc[0:999].

Otherwise, the semantics of using loc are the same as those for iloc.

## Manipulating The Index

Label-based selection derives its power from the labels in the index. Critically, the index we use is not immutable. We can manipulate the index in any way we see fit.

The set_index() method can be used to do the job. Here is what happens when we set_index to the title field:

In [40]:
winemag.set_index("title")

country  \
title                                                          
Nicosia 2013 Vulkà Bianco  (Etna)                      Italy   
Quinta dos Avidagos 2011 Avidagos Red (Douro)       Portugal   
...                                                      ...   
Domaine Marcel Deiss 2012 Pinot Gris (Alsace)         France   
Domaine Schoffit 2012 Lieu-dit Harth Cuvée Caro...    France   

                                                                                          description  \
title                                                                                                   
Nicosia 2013 Vulkà Bianco  (Etna)                   Aromas include tropical fruit, broom, brimston...   
Quinta dos Avidagos 2011 Avidagos Red (Douro)       This is ripe and fruity, a wine that is smooth...   
...                                                                                               ...   
Domaine Marcel Deiss 2012 Pinot Gris (Alsace)       A dry style of Pinot Gris, this is crisp with ...   
Domaine Schoffit 2012 Lieu-dit Harth Cuvée Caro...  Big, rich and off-dry, this is powered by inte...   

                                                                      designation  \
title                                                                               
Nicosia 2013 Vulkà Bianco  (Etna)                                    Vulkà Bianco   
Quinta dos Avidagos 2011 Avidagos Red (Douro)                            Avidagos   
...                                                                           ...   
Domaine Marcel Deiss 2012 Pinot Gris (Alsace)                                 NaN   
Domaine Schoffit 2012 Lieu-dit Harth Cuvée Caro...  Lieu-dit Harth Cuvée Caroline   

                                                    points  price  \
title                                                               
Nicosia 2013 Vulkà Bianco  (Etna)                       87    NaN   
Quinta dos Avidagos 2011 Avidagos Red (Douro)           87   15.0   
...                                                    ...    ...   
Domaine Marcel Deiss 2012 Pinot Gris (Alsace)           90   32.0   
Domaine Schoffit 2012 Lieu-dit Harth Cuvée Caro...      90   21.0   

                                                             province  \
title                                                                   
Nicosia 2013 Vulkà Bianco  (Etna)                   Sicily & Sardinia   
Quinta dos Avidagos 2011 Avidagos Red (Douro)                   Douro   
...                                                               ...   
Domaine Marcel Deiss 2012 Pinot Gris (Alsace)                  Alsace   
Domaine Schoffit 2012 Lieu-dit Harth Cuvée Caro...             Alsace   

                                                   region_1 region_2  \
title                                                                  
Nicosia 2013 Vulkà Bianco  (Etna)                      Etna      NaN   
Quinta dos Avidagos 2011 Avidagos Red (Douro)           NaN      NaN   
...                                                     ...      ...   
Domaine Marcel Deiss 2012 Pinot Gris (Alsace)        Alsace      NaN   
Domaine Schoffit 2012 Lieu-dit Harth Cuvée Caro...   Alsace      NaN   

                                                      taster_name  \
title                                                               
Nicosia 2013 Vulkà Bianco  (Etna)                   Kerin O’Keefe   
Quinta dos Avidagos 2011 Avidagos Red (Douro)          Roger Voss   
...                                                           ...   
Domaine Marcel Deiss 2012 Pinot Gris (Alsace)          Roger Voss   
Domaine Schoffit 2012 Lieu-dit Harth Cuvée Caro...     Roger Voss   

                                                   taster_twitter_handle  \
title                                                                      
Nicosia 2013 Vulkà Bianco  (Etna)                           @kerinokeefe   
Quinta dos Avidagos 2011 Avidagos Red (Douro)              

## Conditional Selection  

So far we've been indexing various strides of data, using structural properties of the DataFrame itself. To do interesting things with the data, however, we often need to ask questions based on conditions.

For example, suppose that we're interested specifically in better-than-average wines produced in Italy.

We can start by checking if each wine is Italian or not:

In [41]:
winemag.country == 'Italy'

0          True
1         False
          ...  
129969    False
129970    False
Name: country, Length: 129971, dtype: bool

This operation produced a Series of True/False booleans based on the country of each record. This result can then be used inside of loc to select the relevant data:

In [43]:
winemag.loc[winemag.country=='Italy']

country                                        description  \
0        Italy  Aromas include tropical fruit, broom, brimston...   
6        Italy  Here's a bright, informal red that opens with ...   
...        ...                                                ...   
129961   Italy  Intense aromas of wild cherry, baking spice, t...   
129962   Italy  Blackberry, cassis, grilled herb and toasted a...   

                      designation  points  price           province  region_1  \
0                    Vulkà Bianco      87    NaN  Sicily & Sardinia      Etna   
6                         Belsito      87   16.0  Sicily & Sardinia  Vittoria   
...                           ...     ...    ...                ...       ...   
129961                        NaN      90   30.0  Sicily & Sardinia   Sicilia   
129962  Sàgana Tenuta San Giacomo      90   40.0  Sicily & Sardinia   Sicilia   

       region_2    taster_name taster_twitter_handle  \
0           NaN  Kerin O’Keefe          @kerinokeefe   
6           NaN  Kerin O’Keefe          @kerinokeefe   
...         ...            ...                   ...   
129961      NaN  Kerin O’Keefe          @kerinokeefe   
129962      NaN  Kerin O’Keefe          @kerinokeefe   

                                                    title       variety  \
0                       Nicosia 2013 Vulkà Bianco  (Etna)   White Blend   
6        Terre di Giurfo 2013 Belsito Frappato (Vittoria)      Frappato   
...                                                   ...           ...   
129961                        COS 2013 Frappato (Sicilia)      Frappato   
129962  Cusumano 2012 Sàgana Tenuta San Giacomo Nero d...  Nero d'Avola   

                 winery  
0               Nicosia  
6       Terre di Giurfo  
...                 ...  
129961              COS  
129962         Cusumano  

[19540 rows x 13 columns]

This DataFrame has ~20,000 rows. The original had ~130,000. That means that around 15% of wines originate from Italy.

We also wanted to know which ones are better than average. Wines are reviewed on a 80-to-100 point scale, so this could mean wines that accrued at least 90 points.

We can use the ampersand (&) to bring the two questions together:

In [44]:
winemag.loc[(winemag.country=='Italy') & (winemag.points >= 90)]

country                                        description  \
120      Italy  Slightly backward, particularly given the vint...   
130      Italy  At the first it was quite muted and subdued, b...   
...        ...                                                ...   
129961   Italy  Intense aromas of wild cherry, baking spice, t...   
129962   Italy  Blackberry, cassis, grilled herb and toasted a...   

                      designation  points  price           province region_1  \
120           Bricco Rocche Prapó      92   70.0           Piedmont   Barolo   
130         Bricco Rocche Brunate      91   70.0           Piedmont   Barolo   
...                           ...     ...    ...                ...      ...   
129961                        NaN      90   30.0  Sicily & Sardinia  Sicilia   
129962  Sàgana Tenuta San Giacomo      90   40.0  Sicily & Sardinia  Sicilia   

       region_2    taster_name taster_twitter_handle  \
120         NaN            NaN                   NaN   
130         NaN            NaN                   NaN   
...         ...            ...                   ...   
129961      NaN  Kerin O’Keefe          @kerinokeefe   
129962      NaN  Kerin O’Keefe          @kerinokeefe   

                                                    title       variety  \
120            Ceretto 2003 Bricco Rocche Prapó  (Barolo)      Nebbiolo   
130          Ceretto 2003 Bricco Rocche Brunate  (Barolo)      Nebbiolo   
...                                                   ...           ...   
129961                        COS 2013 Frappato (Sicilia)      Frappato   
129962  Cusumano 2012 Sàgana Tenuta San Giacomo Nero d...  Nero d'Avola   

          winery  
120      Ceretto  
130      Ceretto  
...          ...  
129961       COS  
129962  Cusumano  

[6648 rows x 13 columns]

Pandas comes with a few built-in conditional selectors, two of which we will highlight here.

The first is isin. isin is lets you select data whose value "is in" a list of values. For example, here's how we can use it to select wines only from Italy or France:

In [45]:
winemag.loc[winemag.country.isin(['Italy','France'])]

country                                        description  \
0        Italy  Aromas include tropical fruit, broom, brimston...   
6        Italy  Here's a bright, informal red that opens with ...   
...        ...                                                ...   
129969  France  A dry style of Pinot Gris, this is crisp with ...   
129970  France  Big, rich and off-dry, this is powered by inte...   

                          designation  points  price           province  \
0                        Vulkà Bianco      87    NaN  Sicily & Sardinia   
6                             Belsito      87   16.0  Sicily & Sardinia   
...                               ...     ...    ...                ...   
129969                            NaN      90   32.0             Alsace   
129970  Lieu-dit Harth Cuvée Caroline      90   21.0             Alsace   

        region_1 region_2    taster_name taster_twitter_handle  \
0           Etna      NaN  Kerin O’Keefe          @kerinokeefe   
6       Vittoria      NaN  Kerin O’Keefe          @kerinokeefe   
...          ...      ...            ...                   ...   
129969    Alsace      NaN     Roger Voss            @vossroger   
129970    Alsace      NaN     Roger Voss            @vossroger   

                                                    title         variety  \
0                       Nicosia 2013 Vulkà Bianco  (Etna)     White Blend   
6        Terre di Giurfo 2013 Belsito Frappato (Vittoria)        Frappato   
...                                                   ...             ...   
129969      Domaine Marcel Deiss 2012 Pinot Gris (Alsace)      Pinot Gris   
129970  Domaine Schoffit 2012 Lieu-dit Harth Cuvée Car...  Gewürztraminer   

                      winery  
0                    Nicosia  
6            Terre di Giurfo  
...                      ...  
129969  Domaine Marcel Deiss  
129970      Domaine Schoffit  

[41633 rows x 13 columns]

The second is isnull (and its companion notnull). These methods let you highlight values which are (or are not) empty (NaN). For example, to filter out wines lacking a price tag in the dataset, here's what we would do:



In [46]:
winemag.loc[(winemag.price.isnull())]

country                                        description  \
0        Italy  Aromas include tropical fruit, broom, brimston...   
13       Italy  This is dominated by oak and oak-driven aromas...   
...        ...                                                ...   
129893   Italy  Aromas of passion fruit, hay and a vegetal not...   
129964  France  Initially quite muted, this wine slowly develo...   

                         designation  points  price           province  \
0                       Vulkà Bianco      87    NaN  Sicily & Sardinia   
13                             Rosso      87    NaN  Sicily & Sardinia   
...                              ...     ...    ...                ...   
129893                  Corte Menini      91    NaN             Veneto   
129964  Domaine Saint-Rémy Herrenweg      90    NaN             Alsace   

              region_1 region_2    taster_name taster_twitter_handle  \
0                 Etna      NaN  Kerin O’Keefe          @kerinokeefe   
13                Etna      NaN  Kerin O’Keefe          @kerinokeefe   
...                ...      ...            ...                   ...   
129893  Soave Classico      NaN  Kerin O’Keefe          @kerinokeefe   
129964          Alsace      NaN     Roger Voss            @vossroger   

                                                    title            variety  \
0                       Nicosia 2013 Vulkà Bianco  (Etna)        White Blend   
13                 Masseria Setteporte 2012 Rosso  (Etna)  Nerello Mascalese   
...                                                   ...                ...   
129893   Le Mandolare 2015 Corte Menini  (Soave Classico)          Garganega   
129964  Domaine Ehrhart 2013 Domaine Saint-Rémy Herren...     Gewürztraminer   

                     winery  
0                   Nicosia  
13      Masseria Setteporte  
...                     ...  
129893         Le Mandolare  
129964      Domaine Ehrhart  

[8996 rows x 13 columns]

## Assigining Data In Pandas

## Summary Functions and Maps

In the last tutorial, we learned how to select relevant data out of a DataFrame or Series. Plucking the right data out of our data representation is critical to getting work done, as we demonstrated in the exercises.

However, the data does not always come out of memory in the format we want it in right out of the bat. Sometimes we have to do some more work ourselves to reformat it for the task at hand. This tutorial will cover different operations we can apply to our data to get the input "just right".

In [61]:
import pandas as pd
pd.set_option("display.max_rows",5)
import numpy as np
winemag = pd.read_csv('/home/kduah/Desktop/ML/02-Pandas/winemag-data-130k-v2.csv',index_col=0)

In [62]:
winemag

country                                        description  \
0          Italy  Aromas include tropical fruit, broom, brimston...   
1       Portugal  This is ripe and fruity, a wine that is smooth...   
...          ...                                                ...   
129969    France  A dry style of Pinot Gris, this is crisp with ...   
129970    France  Big, rich and off-dry, this is powered by inte...   

                          designation  points  price           province  \
0                        Vulkà Bianco      87    NaN  Sicily & Sardinia   
1                            Avidagos      87   15.0              Douro   
...                               ...     ...    ...                ...   
129969                            NaN      90   32.0             Alsace   
129970  Lieu-dit Harth Cuvée Caroline      90   21.0             Alsace   

       region_1 region_2    taster_name taster_twitter_handle  \
0          Etna      NaN  Kerin O’Keefe          @kerinokeefe   
1           NaN      NaN     Roger Voss            @vossroger   
...         ...      ...            ...                   ...   
129969   Alsace      NaN     Roger Voss            @vossroger   
129970   Alsace      NaN     Roger Voss            @vossroger   

                                                    title         variety  \
0                       Nicosia 2013 Vulkà Bianco  (Etna)     White Blend   
1           Quinta dos Avidagos 2011 Avidagos Red (Douro)  Portuguese Red   
...                                                   ...             ...   
129969      Domaine Marcel Deiss 2012 Pinot Gris (Alsace)      Pinot Gris   
129970  Domaine Schoffit 2012 Lieu-dit Harth Cuvée Car...  Gewürztraminer   

                      winery  
0                    Nicosia  
1        Quinta dos Avidagos  
...                      ...  
129969  Domaine Marcel Deiss  
129970      Domaine Schoffit  

[129971 rows x 13 columns]

## Summary Functions

Pandas provides many simple "summary functions" (not an official name) which restructure the data in some useful way. For example, consider the describe() method:

In [63]:
winemag.points.describe()

count    129971.000000
mean         88.447138
             ...      
75%          91.000000
max         100.000000
Name: points, Length: 8, dtype: float64

In [64]:
winemag.country.describe()

count     129908
unique        43
top           US
freq       54504
Name: country, dtype: object

If you want to get some particular simple summary statistic about a column in a DataFrame or a Series, there is usually a helpful pandas function that makes it happen.

For example, to see the mean of the points allotted (e.g. how well an averagely rated wine does), we can use the mean() function

In [65]:
winemag.points.mean()

88.44713820775404

To see a list of unique values we can use the unique() function:



In [66]:
winemag.taster_name.unique()

array(['Kerin O’Keefe', 'Roger Voss', 'Paul Gregutt',
       'Alexander Peartree', 'Michael Schachner', 'Anna Lee C. Iijima',
       'Virginie Boone', 'Matt Kettmann', nan, 'Sean P. Sullivan',
       'Jim Gordon', 'Joe Czerwinski', 'Anne Krebiehl\xa0MW',
       'Lauren Buzzeo', 'Mike DeSimone', 'Jeff Jenssen',
       'Susan Kostrzewa', 'Carrie Dykes', 'Fiona Adams',
       'Christina Pickard'], dtype=object)

To see a list of unique values and how often they occur in the dataset, we can use the value_counts() method:

In [69]:
winemag.taster_name.value_counts()

taster_name
Roger Voss           25514
Michael Schachner    15134
                     ...  
Fiona Adams             27
Christina Pickard        6
Name: count, Length: 19, dtype: int64

## MAPS

A map is a term, borrowed from mathematics, for a function that takes one set of values and "maps" them to another set of values. In data science we often have a need for creating new representations from existing data, or for transforming data from the format it is in now to the format that we want it to be in later. Maps are what handle this work, making them extremely important for getting your work done!

There are two mapping methods that you will use often.

map() is the first, and slightly simpler one. For example, suppose that we wanted to remean the scores the wines received to 0. We can do this as follows:

In [72]:
winemag_points_mean  = winemag.points.mean()
winemag.points.map(lambda p:p - winemag_points_mean)


0        -1.447138
1        -1.447138
            ...   
129969    1.552862
129970    1.552862
Name: points, Length: 129971, dtype: float64

The function you pass to map() should expect a single value from the Series (a point value, in the above example), and return a transformed version of that value. map() returns a new Series where all the values have been transformed by your function.

apply() is the equivalent method if we want to transform a whole DataFrame by calling a custom method on each row

In [73]:
def remean_points(row):
    row.points = row.points - winemag_points_mean
    return row
winemag.apply(remean_points,axis='columns')
    

country                                        description  \
0          Italy  Aromas include tropical fruit, broom, brimston...   
1       Portugal  This is ripe and fruity, a wine that is smooth...   
...          ...                                                ...   
129969    France  A dry style of Pinot Gris, this is crisp with ...   
129970    France  Big, rich and off-dry, this is powered by inte...   

                          designation    points  price           province  \
0                        Vulkà Bianco -1.447138    NaN  Sicily & Sardinia   
1                            Avidagos -1.447138   15.0              Douro   
...                               ...       ...    ...                ...   
129969                            NaN  1.552862   32.0             Alsace   
129970  Lieu-dit Harth Cuvée Caroline  1.552862   21.0             Alsace   

       region_1 region_2    taster_name taster_twitter_handle  \
0          Etna      NaN  Kerin O’Keefe          @kerinokeefe   
1           NaN      NaN     Roger Voss            @vossroger   
...         ...      ...            ...                   ...   
129969   Alsace      NaN     Roger Voss            @vossroger   
129970   Alsace      NaN     Roger Voss            @vossroger   

                                                    title         variety  \
0                       Nicosia 2013 Vulkà Bianco  (Etna)     White Blend   
1           Quinta dos Avidagos 2011 Avidagos Red (Douro)  Portuguese Red   
...                                                   ...             ...   
129969      Domaine Marcel Deiss 2012 Pinot Gris (Alsace)      Pinot Gris   
129970  Domaine Schoffit 2012 Lieu-dit Harth Cuvée Car...  Gewürztraminer   

                      winery  
0                    Nicosia  
1        Quinta dos Avidagos  
...                      ...  
129969  Domaine Marcel Deiss  
129970      Domaine Schoffit  

[129971 rows x 13 columns]

If we had called reviews.apply() with axis='index', then instead of passing a function to transform each row, we would need to give a function to transform each column.

Note that map() and apply() return new, transformed Series and DataFrames, respectively. They don't modify the original data they're called on. If we look at the first row of reviews, we can see that it still has its original points value.

In [74]:
winemag.head(1)

country                                        description   designation  \
0   Italy  Aromas include tropical fruit, broom, brimston...  Vulkà Bianco   

   points  price           province region_1 region_2    taster_name  \
0      87    NaN  Sicily & Sardinia     Etna      NaN  Kerin O’Keefe   

  taster_twitter_handle                              title      variety  \
0          @kerinokeefe  Nicosia 2013 Vulkà Bianco  (Etna)  White Blend   

    winery  
0  Nicosia

In [78]:
winemag_points_mean

88.44713820775404

Pandas provides many common mapping operations as built-ins. For example, here's a faster way of remeaning our points column:

In [77]:
winemag_points_mean = winemag.points.mean()
winemag.points - winemag_points_mean

0        -1.447138
1        -1.447138
            ...   
129969    1.552862
129970    1.552862
Name: points, Length: 129971, dtype: float64

In this code we are performing an operation between a lot of values on the left-hand side (everything in the Series) and a single value on the right-hand side (the mean value). Pandas looks at this expression and figures out that we must mean to subtract that mean value from every value in the dataset.

Pandas will also understand what to do if we perform these operations between Series of equal length. For example, an easy way of combining country and region information in the dataset would be to do the following:

In [80]:
combining_columns = winemag.country + " - " + winemag.region_1
combining_columns

0            Italy - Etna
1                     NaN
               ...       
129969    France - Alsace
129970    France - Alsace
Length: 129971, dtype: object